### PR TITLE
PE-771: 2021-12-08 Görli executive spell

### PR DESCRIPTION
**Pull request by julienmartinlevrai**
# Description

# Contribution Checklist

- [x] PR title starts with `(PE-<TICKET_NUMBER>)`
- [ ] Code approved
- [ ] Tests approved
- [ ] CI Tests pass

# Checklist

- [ ] Every contract variable/method declared as public/external private/internal
- [ ] Consider if this PR needs the `officeHours` modifier
- [ ] Verify expiration (`4 days + 2 hours` monthly and `30 days` for the rest)
- [ ] Verify hash in the description matches [here](https://emn178.github.io/online-tools/keccak_256.html)
- [ ] Validate all addresses used are in Goerli changelog or known
- [ ] Notify any external teams affected by the spell so they have the opportunity to review
- [ ] Deploy spell to Goerli `ETH_GAS="XXX" ETH_GAS_PRICE="YYY" make deploy`
- [ ] Ensure contract is verified on `Goerli` etherscan
- [ ] Change test to use Goerli spell address and deploy timestamp
- [ ] Run `make name="YYYY-MM-DD-archive-directory-name" archive-spell` to make an archive directory and copy `Goerli-DssSpell.sol`, `Goerli-DssSpell.t.sol`, and `Goerli-DssSpell.t.base.sol` 
- [ ] `squash and merge` this PR

### CODE REVIEW

**Comment by iamchrissmith** [comment]
@julienmartinlevrai it won't let me assign you as a reviewer, presumably because you are the original author for this, can you please still review and make sure all looks good to deploy

**Review by julienmartinlevrai — COMMENTED** [review]
:heavy_check_mark: ready for deployment

### G-UNI v3 DAI/USDC 2 onboarding
* onboardNewCollaterals function called in spell action
* spell action inherits from DssSpellCollateralOnboardingAction
* DssSpellCollateralOnboardingAction is imported from DssSpellCollateralOnboarding.sol
* onboardNewCollaterals function is internal
* collateral parameters correspond to https://vote.makerdao.com/polling/QmSkHE8T?network=mainnet#poll-detail
* constants used are correct
* new contracts are only relied to the Pause Proxy
* new contracts are verified on Etherscan
* new contracts have correct parameters
* chainlog names are OK
* chainlog values are OK
* chainlog version bump is only last number
* addresses_goerli have correct names and addresses
* config.sol parameters correspond to https://vote.makerdao.com/polling/QmSkHE8T?network=mainnet#poll-detail
* config.sol imported in Goerli-DssSpell.t.base.sol
* setCollateralValues function called from Goerli-DssSpell.t.base.sol

### Rates updates
* Values correspond to polls
* Rates constants are correct
* 0.1% rate added to rates.sol

**Review by godsflaw — APPROVED** [review]
LGTM

This is a dapptools test run with optimizations on:
```haskell
dapp-test: rpc block: latest
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 7325)
[PASS] test_auth_in_sources() (gas: 5959614)
[PASS] test_use_eta() (gas: 331182)
[PASS] testOnTime() (gas: 3414554)
[PASS] test_nextCastTime() (gas: 332182)
[PASS] testFailTooEarly() (gas: 3833)
[PASS] test_bytecode_matches() (gas: 2314095)
[PASS] test_auth() (gas: 5235659)
[PASS] testSpellIsCast_GENERAL() (gas: 11066033)
[PASS] testFailWrongDay() (gas: 4053)
[PASS] testCollateralIntegrations() (gas: 4362999)
[PASS] testCastCost() (gas: 3416470)
[PASS] testNewChainlogValues() (gas: 3429766)
[PASS] testNewIlkRegistryValues() (gas: 3436279)
[PASS] testFailTooLate() (gas: 4273)
```

**Comment by julienmartinlevrai** [comment]
dapptools tests with optimizations on:

```haskell
dapp-test: rpc block: latest
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 7325)
[PASS] test_auth_in_sources() (gas: 5959354)
[PASS] test_use_eta() (gas: 331182)
[PASS] testOnTime() (gas: 3414294)
[PASS] test_nextCastTime() (gas: 332182)
[PASS] testFailTooEarly() (gas: 3833)
[PASS] test_bytecode_matches() (gas: 2314095)
[PASS] test_auth() (gas: 5235399)
[PASS] testSpellIsCast_GENERAL() (gas: 11065773)
[PASS] testFailWrongDay() (gas: 4053)
[PASS] testCollateralIntegrations() (gas: 4362739)
[PASS] testCastCost() (gas: 3416210)
[PASS] testNewChainlogValues() (gas: 3429506)
[PASS] testNewIlkRegistryValues() (gas: 3436019)
[PASS] testFailTooLate() (gas: 4273)
```

**Comment by brianmcmichael** [comment]
```
dapp-test: rpc block: latest
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 12325)
[PASS] test_auth_in_sources() (gas: 5912763)
[PASS] test_use_eta() (gas: 278482)
[PASS] testOnTime() (gas: 3365703)
[PASS] test_nextCastTime() (gas: 279482)
[PASS] testFailTooEarly() (gas: 8833)
[PASS] test_bytecode_matches() (gas: 2323595)
[PASS] test_auth() (gas: 5188808)
[PASS] testSpellIsCast_GENERAL() (gas: 13324552)
[PASS] testFailWrongDay() (gas: 9053)
[PASS] testCollateralIntegrations() (gas: 4314148)
[PASS] testCastCost() (gas: 3367619)
[PASS] testNewChainlogValues() (gas: 3380915)
[PASS] testNewIlkRegistryValues() (gas: 3387428)
[PASS] testFailTooLate() (gas: 9273)
```

**Comment by julienmartinlevrai** [comment]
dapptools with optimizations
```haskell
dapp-test: rpc block: latest
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 12325)
[PASS] test_auth_in_sources() (gas: 5913253)
[PASS] test_use_eta() (gas: 278482)
[PASS] testOnTime() (gas: 3366193)
[PASS] test_nextCastTime() (gas: 279482)
[PASS] testFailTooEarly() (gas: 8833)
[PASS] test_bytecode_matches() (gas: 2323595)
[PASS] test_auth() (gas: 5189298)
[PASS] testSpellIsCast_GENERAL() (gas: 13325042)
[PASS] testFailWrongDay() (gas: 9053)
[PASS] testCollateralIntegrations() (gas: 4314638)
[PASS] testCastCost() (gas: 3368109)
[PASS] testNewChainlogValues() (gas: 3381405)
[PASS] testNewIlkRegistryValues() (gas: 3387918)
[PASS] testFailTooLate() (gas: 9273)
```
:heavy_check_mark: ready for archiving

**Review by godsflaw — APPROVED** [review]

**Review by brianmcmichael — APPROVED** [review]

**Pull request merged**
