### PR TITLE
[CLEANUP] remove bombshell and archive script and makefile

### PR DESCRIPTION
**Pull request by iamchrissmith**
Clean up PR

We don't need to keep archiving `util/Bombshell.sol` in each spell if we're not using it regularly.  This removes that and moves a copy of the fund script and Makefile to the appropriate archive

### CODE REVIEW

**Comment by brianmcmichael** [comment]
I wonder if we shouldn't just move bombshell.sol and the script out to a new repo entirely and get rid of the references here.

**Review by kmbarry1 — APPROVED** [review]
LGTM

**Comment by kmbarry1** [comment]
> I wonder if we shouldn't just move bombshell.sol and the script out to a new repo entirely and get rid of the references here.

What would the advantage of this be? I like keeping things that were needed for spells within the spell repos.

**Comment by brianmcmichael** [comment]
> What would the advantage of this be? I like keeping things that were needed for spells within the spell repos.

This isn't really a spell action, it was just an operational dependency for a spell to work. Maybe there will be a future need to fund the PP for another reason, but this keeps DAO code visible.

I've hacked up a repo we can move to MakerDAO and then we could remove the commented action from here.

https://github.com/brianmcmichael/bombshell

**Review by The-Arbiter — DISMISSED** [review]
LGTM

**Review by godsflaw — DISMISSED** [review]

**Review by godsflaw — APPROVED** [review]

**Comment by brianmcmichael** [comment]
> I'm fine with having it in a separate repo (probably with some tests too wink )

Test pushed at [3717a15638929b80c0d9356ecccbac144e147f2e](https://github.com/brianmcmichael/bombshell/commit/3717a15638929b80c0d9356ecccbac144e147f2e)

**Pull request merged**
