### PR TITLE
PE-1084: 2022-09-28 Executive Spell

### PR DESCRIPTION
**Pull request by naszam**
# Description

# Contribution Checklist

- [x] PR title starts with `(PE-<TICKET_NUMBER>)`
- [x] Code approved
- [x] Tests approved
- [x] CI Tests pass

# Checklist

- [x] Every contract variable/method declared as public/external private/internal
- [x] Consider if this PR needs the `officeHours` modifier override
- [x] Verify expiration (`30 days` unless otherwise specified)
- [x] Verify hash in the description matches [here](https://emn178.github.io/online-tools/keccak_256.html)
- [x] Validate all addresses used are in Goerli changelog or known
- [x] Notify any external teams affected by the spell so they have the opportunity to review
- [x] Deploy spell to Goerli `ETH_GAS="XXX" ETH_GAS_PRICE="YYY" make deploy`
- [x] Ensure contract is verified on `Goerli` etherscan
- [x] Change test to use Goerli spell address and deploy timestamp
- [x] Cast spell on Goerli `make spell="0x-deployed-spell-address" cast-spell`
- [x] Run `make archive-spell` or `make date="YYYY-MM-DD" archive-spell` to make an archive directory and copy `Goerli-DssSpell.sol`, `Goerli-DssSpell.t.sol`, `Goerli-DssSpell.t.base.sol`, and `Goerli-DssSpellCollateralOnboarding.sol`
- [ ] `squash and merge` this PR

### CODE REVIEW

**Review by godsflaw — DISMISSED** [review]
LGTM ready for deploy

- I move goETH over to the new deployer
- I moved over all the old MKR (wallet controlled and chief locked)
- I locked 100k MKR into the chief on the new deployer

```haskell
Running 1 test for src/test/starknet.t.sol:StarknetTests
[PASS] testStarknet() (gas: 713416)
Test result: ok. 1 passed; 0 failed; finished in 210.54ms

Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testCastCost() (gas: 513468)
[PASS] testFailTooEarly() (gas: 13163)
[PASS] testFailTooLate() (gas: 13140)
[PASS] testFailWrongDay() (gas: 13185)
[PASS] testFail_notScheduled() (gas: 14139)
[PASS] testOnTime() (gas: 509660)
[PASS] testSpellIsCast_GENERAL() (gas: 24410541)
[PASS] testUpdateTeleportFeeds() (gas: 578928)
[PASS] test_auth() (gas: 21434831)
[PASS] test_auth_in_sources() (gas: 5241792)
[PASS] test_bytecode_matches() (gas: 1445007)
[PASS] test_chainlog_values() (gas: 6150724)
[PASS] test_chainlog_version_bump() (gas: 3340029)
[PASS] test_nextCastTime() (gas: 353129)
[PASS] test_use_eta() (gas: 351876)
Test result: ok. 15 passed; 0 failed; finished in 5.93s
```

**Review by godsflaw — APPROVED** [review]
LGTM
- spell verified
- spell's code matches
- uses correct DssExecLib
- correct solidity version
- correct optimizations
- tests pass

Good to:
```bash
spell=0x0e766B170511BBd19380765a8d8673c625d6c61E make cast-spell
make archive-spell
```

```haskell
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 12139)
[PASS] testUpdateTeleportFeeds() (gas: 606128)
[PASS] test_auth_in_sources() (gas: 5244992)
[PASS] test_use_eta() (gas: 350476)
[PASS] testOnTime() (gas: 543360)
[PASS] test_nextCastTime() (gas: 351529)
[PASS] test_chainlog_values() (gas: 5537924)
[PASS] testFailTooEarly() (gas: 9163)
[PASS] test_bytecode_matches() (gas: 1443007)
[PASS] test_chainlog_version_bump() (gas: 3371729)
[PASS] test_auth() (gas: 21438031)
[PASS] testSpellIsCast_GENERAL() (gas: 23727728)
[PASS] testFailWrongDay() (gas: 9185)
[PASS] testCastCost() (gas: 545168)
[PASS] testFailTooLate() (gas: 9140)

Running 1 tests for src/test/starknet.t.sol:StarknetTests
[PASS] testStarknet() (gas: 724616)
```

**Comment by naszam** [comment]
Cast & [Active](https://ethtx.info/goerli/0xe4b5cf81ce4582648622fd61577400dc259a8f8173fef94c9675522e4e132ff3/):

```haskell
spell=0x0e766B170511BBd19380765a8d8673c625d6c61E make cast-spell
./scripts/cast-dssspell.sh 0x0e766B170511BBd19380765a8d8673c625d6c61E
seth send 0x33Ed584fc655b08b2bca45E1C5b5f07c98053bC1 vote(address[] memory) [0x0e766B170511BBd19380765a8d8673c625d6c61E]
seth-send: Published transaction with 100 bytes of calldata.
seth-send: 0x7cb55ce8e9a83c7fd5ade01c2f2267b683ae84c790bcbafd99cee7d738de1ae8
seth-send: Waiting for transaction receipt............
seth-send: Transaction included in block 7663820.

seth send 0x33Ed584fc655b08b2bca45E1C5b5f07c98053bC1 lift(address) 0x0e766B170511BBd19380765a8d8673c625d6c61E
seth-send: Published transaction with 36 bytes of calldata.
seth-send: 0x8f328b98e48747034d5561166cbea0f8bc84d928eccdec1cb6afd7a7763053e9
seth-send: Waiting for transaction receipt.....................
seth-send: Transaction included in block 7663822.

seth send 0x0e766B170511BBd19380765a8d8673c625d6c61E schedule()
seth-send: Published transaction with 4 bytes of calldata.
seth-send: 0xda1fbc09fe2a3fd8db0fb0e71489b91cc2d443e8b516343ad26c2ce9bb24a4ee
seth-send: Waiting for transaction receipt............
seth-send: Transaction included in block 7663823.

waiting for two minutes before casting…
seth send 0x0e766B170511BBd19380765a8d8673c625d6c61E cast()
seth-send: Published transaction with 4 bytes of calldata.
seth-send: 0xe4b5cf81ce4582648622fd61577400dc259a8f8173fef94c9675522e4e132ff3
seth-send: Waiting for transaction receipt....................
seth-send: Transaction included in block 7663834.

Goerli Spell Cast: https://goerli.etherscan.io/address/0x0e766B170511BBd19380765a8d8673c625d6c61E
```

**Review by hexonaut — APPROVED** [review]
Archive matches. Good to merge.

**Review by godsflaw — APPROVED** [review]

**Pull request merged**
