### PR TITLE
PE-965

### PR DESCRIPTION
**Pull request by gbalabasquer**
# Description

# Contribution Checklist

- [ ] PR title starts with `(PE-<TICKET_NUMBER>)`
- [ ] Code approved
- [ ] Tests approved
- [ ] CI Tests pass

# Checklist

- [ ] Every contract variable/method declared as public/external private/internal
- [ ] Consider if this PR needs the `officeHours` modifier override
- [ ] Verify expiration (`30 days` unless otherwise specified)
- [ ] Verify hash in the description matches [here](https://emn178.github.io/online-tools/keccak_256.html)
- [ ] Validate all addresses used are in Goerli changelog or known
- [ ] Notify any external teams affected by the spell so they have the opportunity to review
- [ ] Deploy spell to Goerli `ETH_GAS="XXX" ETH_GAS_PRICE="YYY" make deploy`
- [ ] Ensure contract is verified on `Goerli` etherscan
- [ ] Change test to use Goerli spell address and deploy timestamp
- [ ] Cast spell on Goerli `make spell="0x-deployed-spell-address" cast-spell`
- [ ] Run `make archive-spell` or `make date="YYYY-MM-DD" archive-spell` to make an archive directory and copy `Goerli-DssSpell.sol`, `Goerli-DssSpell.t.sol`, `Goerli-DssSpell.t.base.sol`, and `Goerli-DssSpellCollateralOnboarding.sol`
- [ ] `squash and merge` this PR

### CODE REVIEW

**Review by talbaneth — APPROVED** [review]
Did a quick review, looks good to me.

**Review by naszam — APPROVED** [review]
Tests PASS:
```rust
Running 18 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testCastCost() (gas: 672230)
[PASS] testCollateralIntegrations() (gas: 1510074)
[PASS] testFailTooEarly() (gas: 12550)
[PASS] testFailTooLate() (gas: 12549)
[PASS] testFailWrongDay() (gas: 12572)
[PASS] testFail_notScheduled() (gas: 14139)
[PASS] testNewChainlogValues() (gas: 687457)
[PASS] testOnTime() (gas: 668619)
[PASS] testSpellIsCast_GENERAL() (gas: 21930859)
[PASS] testVestDAI() (gas: 789846)
[PASS] testVestDAIFails() (gas: 974277)
[PASS] test_auth() (gas: 10170632)
[PASS] test_auth_in_sources() (gas: 3962159)
[PASS] test_bytecode_matches() (gas: 1379718)
[PASS] test_chainlog_values() (gas: 5248441)
[PASS] test_chainlog_version_bump() (gas: 2326966)
[PASS] test_nextCastTime() (gas: 341508)
[PASS] test_use_eta() (gas: 340296)
Test result: ok. 18 passed; 0 failed; finished in 2.21s
```
LGTM

**Review by talbaneth — APPROVED** [review]
Recent changes lgtm

**Review by naszam — APPROVED** [review]
Test PASS `00c1728cc1303b4f7dc640dd956cf159bc7af6ce`:
```haskell
dapp-test: rpc block: latest
Running 17 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 7139)
[PASS] test_auth_in_sources() (gas: 3985201)
[PASS] testVestDAIFails() (gas: 1037019)
[PASS] test_use_eta() (gas: 331896)
[PASS] testOnTime() (gas: 714161)
[PASS] testVestDAI() (gas: 850688)
[PASS] test_nextCastTime() (gas: 332819)
[PASS] test_chainlog_values() (gas: 4717505)
[PASS] testFailTooEarly() (gas: 3572)
[PASS] test_bytecode_matches() (gas: 1686661)
[PASS] test_chainlog_version_bump() (gas: 2368530)
[PASS] test_auth() (gas: 10193607)
[PASS] testSpellIsCast_GENERAL() (gas: 20205262)
[PASS] testFailWrongDay() (gas: 3594)
[PASS] testCastCost() (gas: 715772)
[PASS] testNewChainlogValues() (gas: 722499)
[PASS] testFailTooLate() (gas: 3549)
```

LGTDeploy

**Review by naszam — APPROVED** [review]
Checked:

- Deployed Spell Verified
    - Optimization Enabled: No
    - Other Settings: default evmVersion, GNU AGPLv3 license
- Deployed Spell Code Matches GitHub ([diffcheck](https://www.diffchecker.com/XkHO0raG))
- Deploy Timestamp Match
- DssExecLib v0.0.9
- Archive Ok
- Test PASS (with deployed spell):
```haskell
dapp-test: rpc block: latest
Running 17 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 12139)
[PASS] test_auth_in_sources() (gas: 3996701)
[PASS] testVestDAIFails() (gas: 1046519)
[PASS] test_use_eta() (gas: 338896)
[PASS] testOnTime() (gas: 723661)
[PASS] testVestDAI() (gas: 860188)
[PASS] test_nextCastTime() (gas: 339819)
[PASS] test_chainlog_values() (gas: 4729005)
[PASS] testFailTooEarly() (gas: 8572)
[PASS] test_bytecode_matches() (gas: 1696161)
[PASS] test_chainlog_version_bump() (gas: 2380030)
[PASS] test_auth() (gas: 10205107)
[PASS] testSpellIsCast_GENERAL() (gas: 21897538)
[PASS] testFailWrongDay() (gas: 8594)
[PASS] testCastCost() (gas: 725272)
[PASS] testNewChainlogValues() (gas: 731999)
[PASS] testFailTooLate() (gas: 8549)
```
LGTMerge

**Pull request merged**
