### PR TITLE
Remove template directory + Standardize use of pragma

### PR DESCRIPTION
**Pull request by gbalabasquer**
Removing the template directory as not really used.

### CODE REVIEW

**Review by megozu — APPROVED** [review]
LGTM

**Comment by megozu** [comment]
should we bump `forge-std` as well to `v1.2.0`?

**Comment by gbalabasquer** [comment]
> should we bump `forge-std` as well to `v1.2.0`?

Let's leave that for another moment.

**Review by iamchrissmith — APPROVED** [review]
lgtm

**Pull request merged**
