### PR TITLE
PE-805 (Jan 14 2022)

### PR DESCRIPTION
**Pull request by iamchrissmith**
# Description

Update Goerli to reflect the changes from the Jan 14, 2022 executive

# Contribution Checklist

- [ ] PR title starts with `(PE-<TICKET_NUMBER>)`
- [ ] Code approved
- [ ] Tests approved
- [ ] CI Tests pass

# Checklist

- [ ] Every contract variable/method declared as public/external private/internal
- [ ] Consider if this PR needs the `officeHours` modifier
- [ ] Verify expiration (`4 days + 2 hours` monthly and `30 days` for the rest)
- [ ] Verify hash in the description matches [here](https://emn178.github.io/online-tools/keccak_256.html)
- [ ] Validate all addresses used are in Goerli changelog or known
- [ ] Notify any external teams affected by the spell so they have the opportunity to review
- [ ] Deploy spell to Goerli `ETH_GAS="XXX" ETH_GAS_PRICE="YYY" make deploy`
- [ ] Ensure contract is verified on `Goerli` etherscan
- [ ] Change test to use Goerli spell address and deploy timestamp
- [ ] Run `make name="YYYY-MM-DD-archive-directory-name" archive-spell` to make an archive directory and copy `Goerli-DssSpell.sol`, `Goerli-DssSpell.t.sol`, and `Goerli-DssSpell.t.base.sol` 
- [ ] `squash and merge` this PR

### CODE REVIEW

**Comment by iamchrissmith** [comment]
Test passing at block: 6178370

```haskell
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 7747)
[PASS] test_auth_in_sources() (gas: 5999403)
[PASS] test_use_eta() (gas: 333230)
[PASS] testOnTime() (gas: 3431550)
[PASS] test_nextCastTime() (gas: 334449)
[PASS] testFailTooEarly() (gas: 4535)
[PASS] test_bytecode_matches() (gas: 3294151)
[PASS] test_auth() (gas: 5309099)
[PASS] testSpellIsCast_GENERAL() (gas: 12129906)
[PASS] testFailWrongDay() (gas: 4468)
[PASS] testCollateralIntegrations() (gas: 4386241)
[PASS] testCastCost() (gas: 3433263)
[PASS] testNewChainlogValues() (gas: 3446740)
[PASS] testNewIlkRegistryValues() (gas: 3453253)
[PASS] testFailTooLate() (gas: 4489)

```

**Review by julienmartinlevrai — COMMENTED** [review]
#### move Changelog updates to collateral onboarding contract
* moved lines are identical

#### rates update
* commented-out lines from previous spell correspond to new update lines
* update lines correspond to referenced poll
* tests reflect the pre and post values of the poll
* the poll corresponds to the date of the mainnet spell

#### other changes
* no other polls have changes that should be included in the Görli spell

#### tests
* currently running tests

#### Suggestion
* put the "other cleanup changes" section at the end

**Review by julienmartinlevrai — APPROVED** [review]
```haskell
dapp-test: rpc block: latest
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 7325)
[PASS] test_auth_in_sources() (gas: 5961438)
[PASS] test_use_eta() (gas: 331182)
[PASS] testOnTime() (gas: 3416378)
[PASS] test_nextCastTime() (gas: 332182)
[PASS] testFailTooEarly() (gas: 3833)
[PASS] test_bytecode_matches() (gas: 2314095)
[PASS] test_auth() (gas: 5237483)
[PASS] testSpellIsCast_GENERAL() (gas: 11067857)
[PASS] testFailWrongDay() (gas: 4053)
[PASS] testCollateralIntegrations() (gas: 4364823)
[PASS] testCastCost() (gas: 3418294)
[PASS] testNewChainlogValues() (gas: 3431590)
[PASS] testNewIlkRegistryValues() (gas: 3438103)
[PASS] testFailTooLate() (gas: 4273)
```

**Review by godsflaw — APPROVED** [review]
LGTM

```haskell
Running 15 tests for src/Goerli-DssSpell.t.sol:DssSpellTest
[PASS] testFail_notScheduled() (gas: 7747)
[PASS] test_auth_in_sources() (gas: 5995519)
[PASS] test_use_eta() (gas: 333230)
[PASS] testOnTime() (gas: 3427666)
[PASS] test_nextCastTime() (gas: 334449)
[PASS] testFailTooEarly() (gas: 4535)
[PASS] test_bytecode_matches() (gas: 3294151)
[PASS] test_auth() (gas: 5305215)
[PASS] testSpellIsCast_GENERAL() (gas: 12126022)
[PASS] testFailWrongDay() (gas: 4468)
[PASS] testCollateralIntegrations() (gas: 4382357)
[PASS] testCastCost() (gas: 3429379)
[PASS] testNewChainlogValues() (gas: 3442856)
[PASS] testNewIlkRegistryValues() (gas: 3449369)
[PASS] testFailTooLate() (gas: 4489)
```

**Pull request merged**
